export const SINGLE_REQUEST = 'SINGLE_REQUEST'
export const SINGLE_SUCCESS = 'SINGLE_SUCCESS'
export const SINGLE_FAIL = 'SINGLE_FAIL'

export const MULTIPLE_REQUEST = 'MULTIPLE_REQUEST'
export const MULTIPLE_SUCCESS = 'MULTIPLE_SUCCESS'
export const MULTIPLE_FAIL = 'MULTIPLE_FAIL'